version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"

  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"

  #  keycloak_ifood:
  #    container_name: keycloak_ifood
  #    image: jboss/keycloak:9.0.2
  #    environment:
  #      KEYCLOAK_USER: admin
  #      KEYCLOAK_PASSWORD: admin
  #    ports:
  #      - "8180:8080"

  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.11.0
    network_mode: "host"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.17
    ports:
      - "8180:8080"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
